name: build

on:
  workflow_call:
  secrets:
    registry_username:
      required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: check
        uses: actions/checkout@v3
      - name: this is the username
        run: |
          echo  ${{secrets.registry_username}}
      
 
