name: Reusable

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: aristidejoudubois/simpletestreusable/.github/workflows/build.yml@master
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
